[2022-01-21 10:43:44,559] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_basic_dag.dbt_seed manual__2022-01-21T10:43:43.309234+00:00 [queued]>
[2022-01-21 10:43:44,569] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dbt_basic_dag.dbt_seed manual__2022-01-21T10:43:43.309234+00:00 [queued]>
[2022-01-21 10:43:44,569] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-21 10:43:44,569] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-21 10:43:44,569] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-21 10:43:44,579] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): dbt_seed> on 2022-01-21 10:43:43.309234+00:00
[2022-01-21 10:43:44,583] {standard_task_runner.py:52} INFO - Started process 10601 to run task
[2022-01-21 10:43:44,589] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dbt_basic_dag', 'dbt_seed', 'manual__2022-01-21T10:43:43.309234+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dbt_basic.py', '--cfg-path', '/tmp/tmpvtf0bwh8', '--error-file', '/tmp/tmppyxmz500']
[2022-01-21 10:43:44,590] {standard_task_runner.py:77} INFO - Job 3: Subtask dbt_seed
[2022-01-21 10:43:44,661] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_basic_dag.dbt_seed manual__2022-01-21T10:43:43.309234+00:00 [running]> on host c20cfa89904c
[2022-01-21 10:43:44,719] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_basic_dag
AIRFLOW_CTX_TASK_ID=dbt_seed
AIRFLOW_CTX_EXECUTION_DATE=2022-01-21T10:43:43.309234+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-21T10:43:43.309234+00:00
[2022-01-21 10:43:44,721] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-21 10:43:44,721] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt seed --profiles-dir /home/***/.dbt --project-dir /opt/***/dbt']
[2022-01-21 10:43:44,732] {subprocess.py:85} INFO - Output:
[2022-01-21 10:43:47,815] {subprocess.py:89} INFO - Running with dbt=0.21.1
[2022-01-21 10:43:49,894] {subprocess.py:89} INFO - [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2022-01-21 10:43:49,895] {subprocess.py:89} INFO - There are 1 unused configuration paths:
[2022-01-21 10:43:49,895] {subprocess.py:89} INFO - - models.jaffle_shop.staging
[2022-01-21 10:43:49,895] {subprocess.py:89} INFO - 
[2022-01-21 10:43:49,908] {subprocess.py:89} INFO - Found 2 models, 4 tests, 0 snapshots, 0 analyses, 172 macros, 0 operations, 0 seed files, 0 sources, 0 exposures
[2022-01-21 10:43:49,910] {subprocess.py:89} INFO - 
[2022-01-21 10:43:49,910] {subprocess.py:89} INFO - WARNING: Nothing to do. Try checking your model configs and model specification args
[2022-01-21 10:43:49,915] {subprocess.py:89} INFO - 
[2022-01-21 10:43:49,915] {subprocess.py:89} INFO - [32mCompleted successfully[0m
[2022-01-21 10:43:49,916] {subprocess.py:89} INFO - 
[2022-01-21 10:43:49,916] {subprocess.py:89} INFO - Done. PASS=0 WARN=0 ERROR=0 SKIP=0 TOTAL=0
[2022-01-21 10:43:51,430] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-21 10:43:51,461] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dbt_basic_dag, task_id=dbt_seed, execution_date=20220121T104343, start_date=20220121T104344, end_date=20220121T104351
[2022-01-21 10:43:51,489] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-21 10:43:51,523] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
